export enum CategoriesEnum {
  Car = 'Car',
  Motorcycle = 'Motorcycle',
  Boat = 'Boat',
  PartAndAccessory = 'PartAndAccessory',
  HouseSale = 'HouseSale',
  HouseRent = 'HouseRent',
  Land = 'Land',
  CommercialProperty = 'CommercialProperty',
  Job = 'Job',
  Service = 'Service',
  MachineAndEquipment = 'MachineAndEquipment',
  HomeDecor = 'HomeDecor',
  HomeAppliance = 'HomeAppliance',
  AirConditioner = 'AirConditioner',
  Clothe = 'Clothe',
  Accessory = 'Accessory',
  Computer = 'Computer',
  Game = 'Game',
  Mobile = 'Mobile',
  TV = 'TV',
  Sport = 'Sport',
  Book = 'Book',
  Toy = 'Toy',
  Movie = 'Movie',
}

export enum CategoriesFR {
  Car = 'Voitures',
  Motorcycle = 'Motos',
  Boat = 'Bateaux',
  PartAndAccessory = 'Pièces et accessoires',
  HouseSale = 'Maisons à vendre',
  HouseRent = 'Maisons à louer',
  Land = 'Terrains',
  CommercialProperty = 'Propriétés commerciales',
  Job = 'Emplois',
  Service = 'Services',
  MachineAndEquipment = 'Machines et équipements',
  HomeDecor = "Décorations d'intérieur",
  HomeAppliance = 'Appareils électroménagers',
  AirConditioner = 'Climatiseurs',
  Clothe = 'Vêtements',
  Accessory = 'Accessoires',
  Computer = 'Ordinateurs',
  Game = 'Jeux',
  Mobile = 'Téléphones',
  TV = 'Téléviseurs',
  Sport = 'Sport',
  Book = 'Livres',
  Toy = 'Jouets',
  Movie = 'Films',
}

export enum CategoriesEN {
  Car = 'Cars',
  Motorcycle = 'Motorcycles',
  Boat = 'Boats',
  PartAndAccessory = 'Parts and accessories',
  HouseSale = 'Houses for sale',
  HouseRent = 'Houses for rent',
  Land = 'Lands',
  CommercialProperty = 'Commercial properties',
  Job = 'Jobs',
  Service = 'Services',
  MachineAndEquipment = 'Machines and equipments',
  HomeDecor = 'Home Decors',
  HomeAppliance = 'Home Appliances',
  AirConditioner = 'Air conditioners',
  Clothe = 'Clothes',
  Accessory = 'Accessories',
  Computer = 'Computers',
  Game = 'Games',
  Mobile = 'Mobiles',
  TV = 'TVs',
  Sport = 'Sport',
  Book = 'Books',
  Toy = 'Toys',
  Movie = 'Movies',
}
